# ----------------------------------
# Pterodactyl Core Dockerfile
# Environment: Java
# Minimum Panel Version: 1.7.0
# ----------------------------------
FROM ubuntu:22.04

ARG TARGETPLATFORM
ARG GRAAL_VERSION=20.0.2
ARG JAVA_VERSION=20

LABEL author="darksaid98" maintainer="kontakt@riko.dev"

LABEL org.opencontainers.image.source="https://github.com/pterodactyl/yolks"

ENV DEBIAN_FRONTEND=noninteractive

# Default to UTF-8 file.encoding
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'

RUN apt update -y \
	&& apt-get install -y \
	curl \
	lsof \
	ca-certificates \
	openssl \
	git \
	git-lfs \
	tar \
	sqlite3 \
	fontconfig \
	tzdata \
	locales \
	iproute2 \
	libfreetype6 \
	tini \
	&& echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
	&& locale-gen en_US.UTF-8 \
	&& case ${TARGETPLATFORM} in \
	"linux/amd64")  ARCH=x64  ;; \
	"linux/arm64")  ARCH=aarch64  ;; \
	esac \
	&& curl --retry 3 -Lfso /tmp/graalvm.tar.gz https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-${GRAAL_VERSION}/graalvm-community-jdk-${GRAAL_VERSION}_linux-${ARCH}_bin.tar.gz \
	&& mkdir -p /opt/java/graalvm \
	&& cd /opt/java/graalvm \
	&& tar -xf /tmp/graalvm.tar.gz --strip-components=1 \
	&& export PATH="/opt/java/graalvm/bin:$PATH" \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /tmp/graalvm.tar.gz

ENV JAVA_HOME=/opt/java/graalvm \
	PATH="/opt/java/graalvm/bin:$PATH"

## Setup user and working directory
RUN         useradd -m -d /home/container -s /bin/bash container
USER        container
ENV         USER=container HOME=/home/container
WORKDIR     /home/container

STOPSIGNAL SIGINT

COPY        --chown=container:container ./../entrypoint.sh /entrypoint.sh
RUN         chmod +x /entrypoint.sh
ENTRYPOINT    ["/usr/bin/tini", "-g", "--"]
CMD         ["/entrypoint.sh"]
